"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&8u))giwm^$ijd6*iuq2gtj4m%wiqs$k#@%h*jg&rnmu+f*vjq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = 'login'

# Redirect to the book list after successful login
LOGIN_REDIRECT_URL = 'list_books'

# Redirect to the login page after logout
LOGOUT_REDIRECT_URL = 'login'

# Direct Django to stop using the default 'auth.user' and to use the new model instead
AUTH_USER_MODEL = 'bookshelf.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SECURITY CONFIGURATION
# ---------------------------------------------------------

# Only apply these settings in production to avoid breaking local development
if not DEBUG:
    # Step 1: Enforce HTTPS
    
    # Redirects all non-HTTPS requests to HTTPS (http:// -> https://)
    SECURE_SSL_REDIRECT = True 

    # HTTP Strict Transport Security (HSTS)
    # Tells the browser to ONLY connect via HTTPS for the next year (31536000 seconds)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Apply to subdomains (e.g., blog.yoursite.com)
    SECURE_HSTS_PRELOAD = True  # Allow submission to the browser preload list

    # Step 2: Enforce Secure Cookies
    
    # Ensures cookies are only sent over HTTPS connections
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True 

    # Step 3: Implement Secure Headers

    # Prevents the browser from guessing content types (MIME sniffing)
    SECURE_CONTENT_TYPE_NOSENIFF = True

    # Enables the browser's built-in XSS protection
    SECURE_BROWSER_XSS_FILTER = True

    # Prevents your site from being embedded in iframes (Clickjacking protection)
    X_FRAME_OPTIONS = 'DENY'

    # Tell Django to trust the 'X-Forwarded-Proto' header coming
    # from proxy (Nginx/Heroku/etc.)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ALLOWED_HOSTS must be defined when DEBUG IS False
ALLOWED_HOSTS = ['yourdomain.com', 'localhost', '127.0.0.1']

# csp Configuration
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': ("'self'",),
        'style-src': ("'self'", 'https://fonts.googleapis.com'),
    }
}